name: Flask CI/CD Workflows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install Dependencies
      run: |
        echo "python3 -m pip install --upgrade pip"
        echo "pip install -r requirements.txt"
      
    - name: Test App
      run: echo "python3 tests/test.py"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    
    - name: BUilding application
      run: echo "BUilding the app"
  
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: deploy
      env:
        KEY: ${{ secrets.PRIVATEKEY }}
        USER: ${{ secrets.USER }}
        HOST: ${{ secrets.HOST }}
      run: |
        echo "$KEY" > key.pem
        chmod 400 key.pem 
        ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST && sudo apt udate && sudo apt pyhton3-pip && pip install gunicorn && gunicorn -w 4 -b 0.0.0.0:8000 Flaskchess:main && sudo apt install nginx && sudo /etc/nginx/sites=enable/Flaskchess && sudo ln -s /etc/nginx/sites-enabled/Flaskchess /etc/nginx/sites-enabled && sudo systemclt restart nginx && sudo ufw allow 80 && sudo ufw enable
